build_and_upload:
    image: python:3.7.3
    script:
        - pip3 install -U twine
        - python3 setup.py sdist bdist_wheel
        - python3 -m twine --username $PYPI_USERNAME --password $PYPI_PASSWORD upload dist/*
    only:
        - tags
